# Generated by Django 4.1.6 on 2023-03-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.SlugField()),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('price', models.FloatField(default=0, verbose_name='Narxi')),
                ('description', models.TextField(verbose_name='Izox')),
                ('cover', models.ImageField(upload_to='course/images/', verbose_name='Rasm')),
                ('isPublic', models.BooleanField(default=True, verbose_name='Ommaviy/Yashirin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('likes', models.ManyToManyField(related_name='course_likes', to=settings.AUTH_USER_MODEL, verbose_name='Likelar')),
                ('users', models.ManyToManyField(related_name='course_users', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchilar')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.SlugField()),
                ('name', models.CharField(max_length=2000)),
                ('body', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('enders', models.ManyToManyField(related_name='lesson_enders', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='lesson_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
