# Generated by Django 4.1.6 on 2023-03-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problemsets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, default='123', max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('startdate', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=20)),
                ('enddate', models.CharField(max_length=20)),
                ('endtime', models.CharField(max_length=20)),
                ('isPublic', models.BooleanField(default=True)),
                ('isIndividual', models.BooleanField(default=True)),
                ('isContinued', models.CharField(default='notstarted', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('authors', models.ManyToManyField(related_name='contest_authors', to=settings.AUTH_USER_MODEL)),
                ('langs', models.ManyToManyField(related_name='contest_langs', to='problemsets.programminglanguage')),
                ('users', models.ManyToManyField(related_name='contest_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('status', models.TextField(default='{}')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_rating_author', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_rating', to='contests.contest')),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nanoid', models.SlugField()),
                ('name', models.CharField(max_length=1000, verbose_name='Masala nomi')),
                ('problem', models.TextField(verbose_name='Masala matni')),
                ('timelimit', models.IntegerField(verbose_name='Masala vaqt chegarasi(TimeLimit)')),
                ('memorylimit', models.IntegerField(verbose_name='Masala xotira chegarasi(MemoryLimit)')),
                ('difficulty', models.IntegerField(verbose_name='Masala qiyinchiligi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Masala uchun izoh.')),
                ('infoin', models.TextField(blank=True, default="Kirish ma'lumotlari mavjud emas.", null=True, verbose_name="Kirish ma'lumotlari")),
                ('infoout', models.TextField(blank=True, default='Masala javobi.', null=True, verbose_name="Chiqish ma'lumotlari")),
                ('simpletests', models.TextField(blank=True, default='{}', null=True, verbose_name='Simple testlar')),
                ('tests', models.TextField(verbose_name='Testlar')),
                ('solution', models.TextField(blank=True, default='Muallif bu masala yechimini taqdim qilmagan.', null=True, verbose_name='Masalar yechimi.')),
                ('isArchive', models.BooleanField(default=False, verbose_name="Arxivga qo'shish")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='contest_problem_category', to='problemsets.category')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('errors', models.ManyToManyField(related_name='contest_problem_errors', to=settings.AUTH_USER_MODEL)),
                ('solvers', models.ManyToManyField(related_name='contest_problem_solvers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
            ],
        ),
    ]
